### PR TITLE
[do not merge] Standalone modifiers with paren hack

### PR DESCRIPTION
**Pull request by jasonmay**
This is a hardcoded, no-config hack to add the shift-to-parens trick that was made popular by [this article](http://stevelosh.com/blog/2012/10/a-modern-space-cadet/#better-shifting). Build as you would with @wwwjfy's build, but this is only if you want the last piece of the Space Cadet puzzle: better shifting!

**Details of the functionality**: When shift is pressed by itself, it does `(` (or `)` for right shift). When it's pressed in conjunction with something else, it provides the expected behavior.

Required config snippet:
```
            ...
            "standalone_keys": {
                "left_shift": "left_shift",
                "right_shift": "right_shift"
            },
            ...
```

### CODE REVIEW

**Comment by daviesgeek** [comment]
Hmm…I was unable to get this to work after building and setting the config as shown above. Any suggestions?

**Comment by onc** [comment]
hmm... hard to say without any other informations.

did you read this? https://github.com/tekezo/Karabiner-Elements/pull/247#issuecomment-276043287

Things you may have wrong:

* location of configuration. check if you config is at `~/.config/karabiner/karabiner.json` (was `~/.karabiner.d/configuration/` before) 
* configuration itself. try to use my config from the comment linked above.
* try to do a clean reinstall. remove karabiner and all of the config-files. reboot. reinstall and set config again.

**Comment by xxchaos** [comment]
Hi,

I have wired Apple Keyboard with Numeric Keypad.
I would like to remap:
CMD+C to right_CTRL+Fn (copy)
CMD+V to right_SHIFT+Fn (paste)
using Karabiner-Elements.
Can someone help me?

**Comment by IvanRublev** [comment]
Hey @jasonmay, I've made a general patch for shift-to-parens like mappings. Take a look at #2. 
Build is here https://github.com/IvanRublev/Karabiner-Elements/releases/tag/0.90.90_shift_to_parens.

**Comment by jasonmay** [comment]
@IvanRublev awesome! this seems to have gotten fairly out of date anyway (and even stopped working for me at this point). I'll try out yours and if you're works I'll point people to yours!

**Comment by eggsyntax** [comment]
I had great success with @IvanRublev 's build, thanks Ivan!

**Pull request closed without merging**
